Added patches from Fedora Core 8 so that Nvidia compiles fine with Linux 2.6.25. The recipe received a generic support for patches with the extension .manual_patch and for scripts with the extension .run. The Compile automatic patch function doesn't work with this recipe, because we must uncompress the executable in a different fashion here (pre_install()).

diff --git a/trunk/Nvidia/169.12/Recipe b/trunk/Nvidia/169.12/Recipe
--- a/trunk/Nvidia/169.12/Recipe
+++ b/trunk/Nvidia/169.12/Recipe
@@ -30,6 +30,20 @@ pre_install() {
 
     mkdir -p $MODULEDIR
 
+    if [ ! -f AppliedPatches ]
+    then
+       # Run pre-patch scripts, if any
+       for script in $recipedir/*.run
+       do sh $script
+       done
+       # Apply patches
+       for patch in $recipedir/*.manual_patch
+       do
+          patch -i $patch -p1 || { echo "Error applying patch $patch."; exit 1; }
+          echo $patch >> AppliedPatches
+       done
+    fi
+
     # compile
  	./nvidia-installer                                      \
  	--expert                                                \
